version: '3'

services:
  noisy:
    build:
      context: ./
      dockerfile: Dockerfile.pi
    image: noisy:latest
    command: --config config.json
    container_name: noisy
    restart: unless-stopped

